const note_1 = [
  {
    name: "青柠",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1001,
    pinyin: "qingning",
    src: "https://malfoy-mist.top/notes/qingning.jpg",
    description:
      "捏碎带皮果实的酸涩绿感炸裂，白髓微苦随汁液飞溅，尾调残留尖锐清新。",
    intensity: 8,
    freshness: 10,
    sweetness: 3,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "柑橘",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1003,
    pinyin: "ganju",
    src: "https://malfoy-mist.top/notes/ganju_s.jpg",
    description: "阳光橙肉饱满多汁的甜润感，果皮油脂的微涩暖意如指尖残留橙油。",
    intensity: 7,
    freshness: 8,
    sweetness: 6,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "青柚",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1004,
    pinyin: "qingyou",
    src: "https://malfoy-mist.top/notes/qingyou.jpg",
    description: "未熟柚子剖开时青苦水雾弥漫，淡雅花香在冷冽苦韵中悄然绽放。",
    intensity: 6,
    freshness: 7,
    sweetness: 4,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "佛手柑",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1005,
    pinyin: "foshougan",
    src: "https://malfoy-mist.top/notes/foshougan.jpg",
    description: "酸爽柑橘皮包裹伯爵茶的木质尾韵，皂感花香如地中海微风拂过。",
    intensity: 7,
    freshness: 8,
    sweetness: 4,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "香柠檬",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1006,
    pinyin: "xiangningmeng",
    src: "https://malfoy-mist.top/notes/xiangningmeng_x.jpg",
    description: "圆润柠檬香被阳光晒出皂感微光，比普通柠檬更优雅绵长。",
    intensity: 7,
    freshness: 9,
    sweetness: 5,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "橘子",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1007,
    pinyin: "juzi",
    src: "https://malfoy-mist.top/notes/juzi_x.jpg",
    description: "蜜橘汁水爆破般的鲜活甜香，果皮白髓的脂蜡感暗藏基底。",
    intensity: 7,
    freshness: 8,
    sweetness: 6,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "莱姆",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1008,
    pinyin: "laimu",
    src: "https://malfoy-mist.top/notes/laimu.jpg",
    description: "海盐结晶般的尖锐酸爽刺穿感官，加勒比海岛暴晒后的野性青柠。",
    intensity: 8,
    freshness: 9,
    sweetness: 3,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "酸橙",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1009,
    pinyin: "suancheng",
    src: "https://malfoy-mist.top/notes/suancheng.jpg",
    description: "电流般刺激唾液的强酸冲击，尾调未熟青橙的粉末苦感沉淀。",
    intensity: 8,
    freshness: 9,
    sweetness: 3,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "血橙",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1010,
    pinyin: "xiecheng",
    src: "https://malfoy-mist.top/notes/xiecheng.jpg",
    description: "血色果肉撕裂时浆果酸甜喷薄，在经典橙香中凿出鸡尾酒层次。",
    intensity: 7,
    freshness: 8,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "甜橙",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1011,
    pinyin: "tiancheng",
    src: "https://malfoy-mist.top/notes/tiancheng_x.jpg",
    description: "橙汁倾泻般的饱满甜润，果皮白髓的脂蜡感如薄纱轻覆。",
    intensity: 7,
    freshness: 8,
    sweetness: 6,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "葡萄柚",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1012,
    pinyin: "putaoyou",
    src: "https://malfoy-mist.top/notes/putaoyou_x.jpg",
    description: "红柚果肉清冽的微苦特质（诺卡酮核心），汁水充盈间粉甜暗涌。",
    intensity: 7,
    freshness: 8,
    sweetness: 5,
    bitterness: 5,
    dryness: 4,
  },
  {
    name: "柚子-葡萄柚",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1013,
    pinyin: "youzi-putaoyou",
    src: "https://malfoy-mist.top/notes/youzi-putaoyou.jpg",
    description: "苦韵浑厚的复合柚香，苔藓般清冷意境如枯山水庭园晨雾。",
    intensity: 6,
    freshness: 7,
    sweetness: 4,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "西柚",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "柑橘类",
    global_id: 1021,
    pinyin: "xiyou",
    src: "https://malfoy-mist.top/notes/xiyou.jpg",
    description: "血色果肉撒盐般的苦甜博弈，酸度如玻璃锋芒划破甜腻。",
    intensity: 7,
    freshness: 8,
    sweetness: 5,
    bitterness: 5,
    dryness: 4,
  },
  {
    name: "橄榄",
    category: ["top"],
    olfactory_family: "绿叶调",
    sub_olfactory_family: "绿意果香",
    global_id: 1000,
    pinyin: "ganlan",
    src: "https://malfoy-mist.top/notes/ganlan.jpg",
    description: "枝叶折断瞬间迸射青涩汁液，油脂般苦感如咬碎橄榄核的髓质。",
    intensity: 6,
    freshness: 6,
    sweetness: 3,
    bitterness: 7,
    dryness: 4,
  },
  {
    name: "青苹果",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1002,
    pinyin: "qingpingguo",
    src: "https://malfoy-mist.top/notes/qingpingguo_x.jpg",
    description:
      "咬开未熟苹果的脆响！酸绿锐气穿透果核微涩，晨露沾湿的果园气息。",
    intensity: 6,
    freshness: 7,
    sweetness: 4,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "黄瓜",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1015,
    pinyin: "huanggua",
    src: "https://malfoy-mist.top/notes/huanggua.jpg",
    description: "瓜瓤水润清甜过渡到青皮草本涩感，夏日凉风穿藤蔓的写意。",
    intensity: 5,
    freshness: 7,
    sweetness: 4,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "樱桃",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1018,
    pinyin: "yingtao",
    src: "https://malfoy-mist.top/notes/yingtao_x.jpg",
    description: "糖渍蜜感包裹杏仁苦核，枝叶酸绿在暗处沙沙作响（苯甲醛基底）。",
    intensity: 6,
    freshness: 6,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "荔枝",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1023,
    pinyin: "lizhi",
    src: "https://malfoy-mist.top/notes/lizhi_x.jpg",
    description: "玫瑰甜香浸润半透明果肉，凝露般汁水垂坠欲滴的鲜活。",
    intensity: 6,
    freshness: 6,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "葡萄",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1024,
    pinyin: "putao",
    src: "https://malfoy-mist.top/notes/putao.jpg",
    description: "麝香葡萄特有的微醺酒意，果皮单宁涩感如浅酌未醒的酒液。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "草莓",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1025,
    pinyin: "caomei",
    src: "https://malfoy-mist.top/notes/caomei.jpg",
    description: "野生草莓萼片的酸绿平衡奶油甜香，齿间迸裂的红色浆液感。",
    intensity: 6,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "蓝莓",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1026,
    pinyin: "lanmei",
    src: "https://malfoy-mist.top/notes/lanmei.png",
    description: "果霜粉感覆盖酒渍深甜，熟透果肉发酵出醉人韵律。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "黑加侖子",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1027,
    pinyin: "heijialunzi",
    src: "https://malfoy-mist.top/notes/heijialunzi.jpg",
    description:
      "猫尿般的野性气息被浆果甜驯服（布枯叶醚），枝叶青腥如雨后灌木丛。",
    intensity: 6,
    freshness: 5,
    sweetness: 5,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "覆盆子",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1033,
    pinyin: "fupenzi",
    src: "https://malfoy-mist.top/notes/fupenzi.jpeg",
    description: "果酱浓甜交织木质粉感，酸度如红宝石切面折射光芒。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "水蜜桃",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1020,
    pinyin: "shuimitao",
    src: "https://malfoy-mist.top/notes/shuimitao_x.jpg",
    description: "绒毛触感的熟桃甜香（桃醛标志），近核处奶蜡感与微苦交融。",
    intensity: 6,
    freshness: 6,
    sweetness: 7,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "李子",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1022,
    pinyin: "lizi",
    src: "https://malfoy-mist.top/notes/lizi.jpg",
    description: "深紫果霜下的饱满酸甜，杏仁苦韵如咬碎桃核的意外转折。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "洋梨",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1034,
    pinyin: "yangli",
    src: "https://malfoy-mist.top/notes/yangli.jpg",
    description: "沙脆果肉融化成黄油熟甜，秋日梨园阳光烘焙的暖意。",
    intensity: 6,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "苹果",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "绿意果香",
    global_id: 1030,
    pinyin: "pingguo",
    src: "https://malfoy-mist.top/notes/pingguo.jpg",
    description: "红苹果经典甜脆裹着果皮微蜡，咬下瞬间汁水鲜活的喘息。",
    intensity: 6,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "香蕉",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "热带果香",
    global_id: 1014,
    pinyin: "xiangjiao",
    src: "https://malfoy-mist.top/notes/xiangjiao.jpeg",
    description:
      "熟透果肉的浓郁甜香（乙酸异戊酯核心），发酵酒意如热带集市喧嚣。",
    intensity: 6,
    freshness: 5,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "百香果",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "热带果香",
    global_id: 1016,
    pinyin: "baixiangguo",
    src: "https://malfoy-mist.top/notes/baixiangguo_x.jpg",
    description: "甜酸包裹微臭果核的野性（硫醇特征），复杂如打翻的香水调色盘。",
    intensity: 6,
    freshness: 6,
    sweetness: 7,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "西瓜",
    category: ["top", "middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "热带果香",
    global_id: 1017,
    pinyin: "xigua",
    src: "https://malfoy-mist.top/notes/xigua.png",
    description: "瓜瓤淡雅甜润与瓜皮青涩水感交融，绿纹红瓤的夏日解渴图腾。",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "哈密瓜",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "热带果香",
    global_id: 1028,
    pinyin: "hamigua",
    src: "https://malfoy-mist.top/notes/hamigua.png",
    description: "蜜甜果肉边缘碰撞瓜皮泥土青绿，藤蔓阴影下的甜蜜诱惑。",
    intensity: 6,
    freshness: 6,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "菠萝",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "热带果香",
    global_id: 1029,
    pinyin: "boluo",
    src: "https://malfoy-mist.top/notes/boluo_x.jpg",
    description: "热带甜酸风暴席卷味蕾，果芯微涩木质如雨后凤梨田的收束。",
    intensity: 6,
    freshness: 6,
    sweetness: 7,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "无花果",
    category: ["middle"],
    olfactory_family: "果香调",
    sub_olfactory_family: "青绿木质类",
    global_id: 1019,
    pinyin: "wuhuaguo",
    src: "https://malfoy-mist.top/notes/wuhuaguo.jpg",
    description:
      "青绿汁液×乳白树汁×木质根茎三维交响——踏入地中海无花果林的绿意穹顶。",
    intensity: 5,
    freshness: 6,
    sweetness: 5,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "椰子",
    category: ["middle", "base"],
    olfactory_family: ["果香调", "美食调"],
    sub_olfactory_family: "奶脂类",
    global_id: 1031,
    pinyin: "yezi",
    src: "https://malfoy-mist.top/notes/yezi.jpg",
    description: "奶油甜香如椰浆倾泻（γ-壬内酯核心），果肉纤维感拉回沙滩实境。",
    intensity: 6,
    freshness: 4,
    sweetness: 8,
    bitterness: 2,
    dryness: 3,
  },
  {
    name: "杏仁",
    category: ["base"],
    olfactory_family: ["果香调", "东方香调", "美食调"],
    sub_olfactory_family: "坚果类",
    global_id: 1032,
    pinyin: "xingren",
    src: "https://malfoy-mist.top/notes/xingren.jpg",
    description:
      "油脂包裹的苦杏核气息（苯甲醛核心），被香草柔化成烘焙坊的暖甜雾霭。",
    intensity: 6,
    freshness: 3,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
];

const note_2 = [
  {
    name: "红玫瑰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "玫瑰类",
    global_id: 2000,
    pinyin: "hongmeigui",
    src: "https://malfoy-mist.top/notes/hongmeigui_x.jpg",
    description:
      "经典蜂蜜甜香包裹着湿润花瓣气息，含苯乙醇与香茅醇，温暖馥郁中带清透果香。",
    intensity: 6,
    freshness: 5,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "白玫瑰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "玫瑰类",
    global_id: 2001,
    pinyin: "baimeigui",
    src: "https://malfoy-mist.top/notes/baimeigui_x.jpg",
    description:
      "青绿涩感交织清冷花香，β-大马香茅酮赋予晨露般的澄澈微甜，如初绽花瓣。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "保加利亚玫瑰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "玫瑰类",
    global_id: 2002,
    pinyin: "baojialiyameigui",
    src: "https://malfoy-mist.top/notes/baojialiyameigui.jpg",
    description:
      "大马士革酮主导的奢华蜂蜜荔枝香，糅合丁香酚的辛甜，饱满如丝绒花瓣。",
    intensity: 6,
    freshness: 5,
    sweetness: 8,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "五月玫瑰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "玫瑰类",
    global_id: 2003,
    pinyin: "wuyuemeigui",
    src: "https://malfoy-mist.top/notes/wuyuemeigui_x.jpg",
    description:
      "玫瑰醚与柠檬醛碰撞出青柠般的鲜活果香，透出绿茶清韵，灵动不甜腻。",
    intensity: 5,
    freshness: 8,
    sweetness: 5,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "粉玫瑰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "玫瑰类",
    global_id: 2004,
    pinyin: "fenmeigui",
    src: "https://malfoy-mist.top/notes/fenmeigui.jpg",
    description: "苯乙醇带来清甜皂感，天竺葵烯模拟枝叶青绿，似沾露的荔枝玫瑰。",
    intensity: 5,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "蔷薇",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "玫瑰类",
    global_id: 2005,
    pinyin: "qiangwei",
    src: "https://malfoy-mist.top/notes/qiangwei.jpg",
    description:
      "野性单萜烯香气混合泥土草本感，玫瑰酮赋予酸涩莓果调，宛如荆棘丛生。",
    intensity: 6,
    freshness: 5,
    sweetness: 5,
    bitterness: 6,
    dryness: 5,
  },
  {
    name: "晚香玉",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2006,
    pinyin: "wanxiangyu",
    src: "https://malfoy-mist.top/notes/wanxiangyu.jpg",
    description: "苯甲酸苄酯的奶油甜润包裹吲哚的动物感，如月下绽放的丰腴白花。",
    intensity: 6,
    freshness: 5,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "白兰花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2007,
    pinyin: "bailanhua",
    src: "https://malfoy-mist.top/notes/bailanhua.jpg",
    description:
      "芳樟醇主导的茶香清韵，α-萜品醇携嫩叶青涩，复刻江南街巷的湿润白玉香。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "茉莉",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2008,
    pinyin: "moli",
    src: "https://malfoy-mist.top/notes/moli.jpg",
    description:
      "乙酸苄酯的清甜与吲哚的腥暖交织，大花茉莉具皮革底蕴，小花茉莉更清透。",
    intensity: 6,
    freshness: 6,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "阿拉伯茉莉",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2009,
    pinyin: "alabomoli",
    src: "https://malfoy-mist.top/notes/alabomoli_x.jpg",
    description: "高比例芳樟醇削弱吲哚，突出柑橘与茶香，轻盈如风中的星形白花。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "荷花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2010,
    pinyin: "hehua",
    src: "https://malfoy-mist.top/notes/hehua_x.jpg",
    description:
      "水感苯乙醇与莲酮营造清冷睡莲，微带黄瓜醛的水生绿意，空灵出尘。",
    intensity: 5,
    freshness: 8,
    sweetness: 5,
    bitterness: 3,
    dryness: 2,
  },
  {
    name: "木棉花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2011,
    pinyin: "mumianhua",
    src: "https://malfoy-mist.top/notes/mumianhua.jpg",
    description:
      "苯甲酸甲酯的香蕉甜香混合干草气息，蜜蜡底韵如晒暖的棉絮，温厚少粉感。",
    intensity: 5,
    freshness: 5,
    sweetness: 6,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "康乃馨",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2012,
    pinyin: "kangnaixin",
    src: "https://malfoy-mist.top/notes/kangnaixin_x.jpg",
    description: "丁香油酚的辛辣丁香调，融合香荚兰豆的甜粉，复古而略带药感。",
    intensity: 5,
    freshness: 5,
    sweetness: 6,
    bitterness: 5,
    dryness: 4,
  },
  {
    name: "小雏菊",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2013,
    pinyin: "xiaochuju",
    src: "https://malfoy-mist.top/notes/xiaochuju.jpg",
    description:
      "乙酸叶醇酯的青苹果脆爽感主导，微带紫罗兰叶的黄瓜绿意，春日野草地般清新。",
    intensity: 5,
    freshness: 8,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "夜来香",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2014,
    pinyin: "yelaixiang",
    src: "https://malfoy-mist.top/notes/yelaixiang.jpg",
    description:
      "高浓度吲哚赋予腐败暖甜，苯甲酸苄酯包裹奶油感，如夏夜暗香涌动。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "忍冬花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2015,
    pinyin: "rendonghua",
    src: "https://malfoy-mist.top/notes/rendonghua.jpg",
    description: "芳樟醇与叶醇的嫩绿青草香，忍冬内酯赋予清冷微苦，似雨后藤蔓。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "丁香",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2016,
    pinyin: "dingxiang",
    src: "https://malfoy-mist.top/notes/dingxiang.jpg",
    description:
      "丁香酚的辛辣药感占80%，融合石竹烯木质底蕴，复古而略带金属凉意。",
    intensity: 6,
    freshness: 5,
    sweetness: 5,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "勿忘我",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2017,
    pinyin: "wuwangwo",
    src: "https://malfoy-mist.top/notes/wuwangwo.jpg?imageMogr2/thumbnail/200x",
    description: "甲酸香叶酯的青草酸涩与苯甲醛杏仁核香，淡雅粉感似干燥花束",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "睡莲",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2018,
    pinyin: "shuilian",
    src: "https://malfoy-mist.top/notes/shuilian.jpg",
    description:
      "水杨酸戊酯的水生清冷调，莲酮赋予黄瓜皮般的青绿空灵，不涉动物感。",
    intensity: 5,
    freshness: 8,
    sweetness: 5,
    bitterness: 3,
    dryness: 2,
  },
  {
    name: "薰衣草",
    category: ["top", "middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2019,
    pinyin: "xunyicao",
    src: "https://malfoy-mist.top/notes/xunyicao.jpg",
    description:
      "芳樟醇与乙酸芳樟酯主导，清冽草药香交织甜脂粉感，兼具镇静与暖意。",
    intensity: 6,
    freshness: 6,
    sweetness: 5,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "胡姬花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2020,
    pinyin: "hujihua",
    src: "https://malfoy-mist.top/notes/hujihua.jpg",
    description: "香兰素的奶甜基底，苯乙醇提亮花香，蜡质大花蕊具微醺蜜感。",
    intensity: 5,
    freshness: 5,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "风信子",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2021,
    pinyin: "fengxinzi",
    src: "https://malfoy-mist.top/notes/fengxinzi_x.jpg",
    description:
      "苯甲醛的苦杏仁核香，桂醇催生绿意辛辣，风信子醛强化土腥绽放感。",
    intensity: 5,
    freshness: 6,
    sweetness: 4,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "郁金香",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2022,
    pinyin: "yujinxiang",
    src: "https://malfoy-mist.top/notes/yujinxiang.jpg",
    description:
      "叶醇的茎汁青涩感，β-紫罗兰酮模拟花粉粉韵，如折断花茎的汁液香。",
    intensity: 5,
    freshness: 6,
    sweetness: 4,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "姜花（蝴蝶花）",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2023,
    pinyin: "jianghua（hudiehua）",
    src: "https://malfoy-mist.top/notes/jianghua（hudiehua）.jpg",
    description:
      "柠檬烯与金合欢烯共塑清甜姜汁，微带乙酸香叶酯的玫瑰余韵，雨后般水润。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "山茶花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2025,
    pinyin: "shanchahua",
    src: "https://malfoy-mist.top/notes/shanchahua.jpg",
    description:
      "苯甲醇的干草甜香，吲哚微量点缀，茶醛赋予枝叶苦绿，似白茶与花瓣交织。",
    intensity: 5,
    freshness: 6,
    sweetness: 5,
    bitterness: 5,
    dryness: 4,
  },
  {
    name: "牡丹",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2026,
    pinyin: "mudan",
    src: "https://malfoy-mist.top/notes/mudan_x.jpg",
    description:
      "玫瑰醚的果甜、水杨酸苄酯的粉感，覆盆子香基模拟酸甜浆果，雍容不厚重。",
    intensity: 5,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "洛神花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2027,
    pinyin: "luoshenhua",
    src: "https://malfoy-mist.top/notes/luoshenhua.jpg",
    description:
      "大量柠檬酸与木槿酸构筑尖锐果酸，花青素般微涩，近似山楂与浆果。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "罂粟花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2028,
    pinyin: "yingsuhua",
    src: "https://malfoy-mist.top/notes/yingsuhua.jpg",
    description: "紫罗兰酮的粉甜作基底，没药树脂模拟鸦片膏苦腥，暗藏危险诱惑。",
    intensity: 5,
    freshness: 5,
    sweetness: 6,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "依兰",
    category: ["middle", "base"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2029,
    pinyin: "yilan",
    src: "https://malfoy-mist.top/notes/yilan.jpg",
    description:
      "苯甲酸甲酯的香蕉甜香混合丁香酚的辛辣，热带感丰腴，略带橡胶底蕴。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "橙花",
    category: ["top", "middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2030,
    pinyin: "chenghua",
    src: "https://malfoy-mist.top/notes/chenghua_x.jpg",
    description: "苦橙萜烯与乙酸芳樟酯共舞，清苦橘皮混糅皂感白花，洁净而明亮。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "铃兰",
    category: ["top", "middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2031,
    pinyin: "linglan",
    src: "https://malfoy-mist.top/notes/linglan.jpg",
    description: "羟基香茅醛构筑水润青绿感，铃兰醛赋予嫩叶与花瓣的脆嫩清甜。",
    intensity: 5,
    freshness: 8,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "紫罗兰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2032,
    pinyin: "ziluolan",
    src: "https://malfoy-mist.top/notes/ziluolan.jpg",
    description: "紫罗兰酮的粉质鸢尾根气息，含微咸土壤感，叶片则具黄瓜般青脆。",
    intensity: 5,
    freshness: 6,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "金银花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2033,
    pinyin: "jinyinhua",
    src: "https://malfoy-mist.top/notes/jinyinhua.jpg",
    description:
      "金合欢烯与芳樟醇共塑蜂蜜水清甜，微带药草凉意，如藤蔓间垂落之花。",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "兰花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2034,
    pinyin: "lanhua",
    src: "https://malfoy-mist.top/notes/lanhua.jpg",
    description:
      "茴香醛的粉甜与松油醇清冷绿意交融，蜡质般的幽香透微凉，似空谷幽兰。",
    intensity: 5,
    freshness: 6,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "桃花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2035,
    pinyin: "taohua",
    src: "https://malfoy-mist.top/notes/taohua_x.jpg",
    description:
      "γ-癸内酯的蜜桃果香交织苯乙醇花瓣清甜，醛香赋予水润感，如春日枝头带露绽放。",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "桂花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2036,
    pinyin: "guihua",
    src: "https://malfoy-mist.top/notes/guihua.jpg",
    description: "紫罗兰酮的粉感桃杏香，γ-癸内酯的奶甜，似糖渍花瓣与秋日暖阳。",
    intensity: 5,
    freshness: 6,
    sweetness: 7,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "黄葵",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2037,
    pinyin: "huangkui",
    src: "https://malfoy-mist.top/notes/huangkui.jpg",
    description: "麝香酮的肌肤暖甜与秋葵籽的壤香，独特动物感如日光晒暖的种子。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "栀子花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2038,
    pinyin: "zhizihua",
    src: "https://malfoy-mist.top/notes/zhizihua.jpg",
    description:
      "乙酸苏合香脂的奶油桃香，苯甲酸叶酯的绿叶青涩，复刻绵密花瓣质地。",
    intensity: 5,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "白玉兰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2039,
    pinyin: "baiyulan",
    src: "https://malfoy-mist.top/notes/baiyulan.jpeg",
    description:
      "芳樟醇爆发的清甜茶香，揉碎嫩叶的青涩汁液（α-松油醇），雨后白玉般水润生凉。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "樱花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2040,
    pinyin: "yinghua",
    src: "https://malfoy-mist.top/notes/yinghua.jpg",
    description:
      "苯甲醛的杏仁奶韵托起花瓣，覆盆子酮溅出浆果酸汁，粉雾随风散落。",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "梅花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2041,
    pinyin: "meihua",
    src: "https://malfoy-mist.top/notes/meihua.jpg",
    description:
      "苯甲酸甲酯的蜜蜡冷甜穿刺寒风，腊梅烯赋予冰晶质感，枯枝清苦萦绕。",
    intensity: 5,
    freshness: 5,
    sweetness: 5,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "水仙花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2042,
    pinyin: "shuixianhua",
    src: "https://malfoy-mist.top/notes/shuixianhua.jpg",
    description:
      "对甲酚的动物腥臊（＜0.3%）纠缠青根汁液，苯乙醇花瓣渗出腐败蜜感。",
    intensity: 6,
    freshness: 5,
    sweetness: 4,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "鸡蛋花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2043,
    pinyin: "jidanhua",
    src: "https://malfoy-mist.top/notes/jidanhua.jpg",
    description:
      "苯甲酸顺式-3-己烯酯的奶油芒果甜，被金合欢醇蜜香浸泡，烈日炙烤下流淌。",
    intensity: 5,
    freshness: 6,
    sweetness: 7,
    bitterness: 2,
    dryness: 3,
  },
  {
    name: "海棠花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2044,
    pinyin: "haitanghua",
    src: "https://malfoy-mist.top/notes/haitanghua.jpg",
    description: "苯乙醛切开青苹果脆皮，丙位癸内酯渗出桃肉粉甜，酸涩汁液迸溅。",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "百合花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2045,
    pinyin: "baihehua",
    src: "https://malfoy-mist.top/notes/baihehua_x.jpg",
    description: "松油醇碾碎辛辣绿叶，乙酸香叶酯滴落发酵花蜜，花粉浓稠窒息。",
    intensity: 6,
    freshness: 5,
    sweetness: 5,
    bitterness: 4,
    dryness: 4,
  },
  {
    name: "鸢尾花",
    category: ["middle", "base"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 2046,
    pinyin: "yuanweihua",
    src: "https://malfoy-mist.top/notes/yuanweihua_x.jpg",
    description:
      "鸢尾酮脂粉蓬松如旧妆匣，十四醛融成黄油咸香，根茎撬出湿土金属。",
    intensity: 6,
    freshness: 4,
    sweetness: 4,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "风铃草",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "白花类",
    global_id: 5005,
    pinyin: "fenglingcao",
    src: "https://malfoy-mist.top/notes/fenglingcao_x.jpg",
    description:
      "乙酸叶醇酯劈开青苹果皮，水杨酸甲酯泼洒薄荷药凉，铃兰醛摇响水甜。",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "甘菊",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2024,
    pinyin: "ganju",
    src: "https://malfoy-mist.top/notes/ganju_x.jpg",
    description:
      "母菊薁的深蓝药苦穿刺干草堆，当归酸裹着结晶蜜块，沉入菊花茶底。",
    intensity: 5,
    freshness: 5,
    sweetness: 4,
    bitterness: 6,
    dryness: 3,
  },
  {
    name: "洋甘菊",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2047,
    pinyin: "yangganju",
    src: "https://malfoy-mist.top/notes/yangganju.jpg",
    description:
      "母菊薁的深蓝药苦穿刺干草堆，当归酸结晶蜜块沉底，晒干菊瓣浮起清苦茶韵",
    intensity: 5,
    freshness: 5,
    sweetness: 4,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "百里香",
    category: ["top", "middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2048,
    pinyin: "bailixiang",
    src: "https://malfoy-mist.top/notes/bailixiang.jpg",
    description:
      "百里酚的尖锐药感劈开干燥土壤，香荆芥酚撒出胡椒星火，揉碎枝叶渗出青绿树脂",
    intensity: 6,
    freshness: 6,
    sweetness: 3,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "马郁兰",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2049,
    pinyin: "mayulan",
    src: "https://malfoy-mist.top/notes/mayulan.jpg",
    description:
      "松油烯的樟脑凉意缠绕甜橙花，乙酸芳樟酯溅出皂感露珠，药草束暖意氤氲升腾",
    intensity: 5,
    freshness: 6,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "迷迭香",
    category: ["top", "middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2050,
    pinyin: "midiexiang",
    src: "https://malfoy-mist.top/notes/midiexiang_x.jpg",
    description:
      "桉叶油素炸开冰冽樟脑锋刃，α-蒎烯刺穿松针林雾，折断枝干滴落琥珀松脂",
    intensity: 6,
    freshness: 7,
    sweetness: 3,
    bitterness: 5,
    dryness: 4,
  },
  {
    name: "月桂",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2051,
    pinyin: "yuegui",
    src: "https://malfoy-mist.top/notes/yuegui.jpg",
    description:
      "丁香酚的辛辣甜香裹挟芳樟醇茶韵，碾碎叶片渗出杏仁奶咸，烘焙香料暖意盘旋",
    intensity: 5,
    freshness: 5,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
  {
    name: "藏红花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "芳香草本类",
    global_id: 2054,
    pinyin: "canghonghua",
    src: "https://malfoy-mist.top/notes/canghonghua_x.jpg",
    description:
      "藏红花醛的金属苦腥穿刺皮革，苦藏花素渗出干草蜜甜，番红花蕊灼烧出烟熏橙皮",
    intensity: 6,
    freshness: 4,
    sweetness: 4,
    bitterness: 6,
    dryness: 4,
  },
  {
    name: "小苍兰",
    category: ["top", "middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2052,
    pinyin: "xiaocanglan",
    src: "https://malfoy-mist.top/notes/xiaocanglan_x.jpg",
    description:
      "苯甲酸甲酯的粉甜花瓣裹挟叶醇青茎汁液，铃兰醛摇响水润脆铃，早春花田薄雾弥漫",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "田野花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2053,
    pinyin: "tianyehua",
    src: "https://malfoy-mist.top/notes/tianyehua.jpg",
    description:
      "苯乙醛的蜂蜜甜腻泼洒雏菊花海，金合欢醇蜜蜡裹挟蒲公英绒球，风卷青草酸涩",
    intensity: 5,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "菊花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2055,
    pinyin: "juhua",
    src: "https://malfoy-mist.top/notes/juhua_x.jpg",
    description:
      "白菊酮的清凉药苦刺穿干花瓣，樟脑撒出冰晶粉尘，尾韵浮起晒秋菊的微甘",
    intensity: 5,
    freshness: 6,
    sweetness: 4,
    bitterness: 5,
    dryness: 3,
  },
  {
    name: "太阳花",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2056,
    pinyin: "taiyanghua",
    src: "https://malfoy-mist.top/notes/taiyanghua.jpg",
    description:
      "苯乙醇的蜜糖花瓣铺满田野，β-石竹烯树脂裹挟葵籽油香，烈日炙烤花粉浓稠流淌",
    intensity: 5,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "蓝风铃",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2057,
    pinyin: "lanfengling",
    src: "https://malfoy-mist.top/notes/lanfengling_x.jpg",
    description:
      "西瓜酮的水感甜韵托起风铃草，乙酸叶醇酯劈开青瓜脆皮，丁酸叶醇酯溅出野莓酸汁",
    intensity: 5,
    freshness: 7,
    sweetness: 6,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "天竺葵",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2058,
    pinyin: "tianzhukui",
    src: "https://malfoy-mist.top/notes/tianzhukui_x.jpg",
    description:
      "香茅醇的柠檬玫瑰甜香被甲酸香叶酯削出青叶锐边，薄荷凉意掠过毛绒叶片",
    intensity: 5,
    freshness: 7,
    sweetness: 5,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "辣木",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "绿意花香类",
    global_id: 2059,
    pinyin: "lamu",
    src: "https://malfoy-mist.top/notes/lamu.jpg",
    description:
      "苯乙醛释放蜜香基调，青柠醛交织绿叶辛香，尾韵呈现微妙异硫氰酸酯辛辣感",
    intensity: 6,
    freshness: 6,
    sweetness: 5,
    bitterness: 4,
    dryness: 3,
  },
];

const note_3 = [
  {
    name: "檀香",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 3000,
    pinyin: "tanxiang",
    src: "https://malfoy-mist.top/notes/tanxiang.jpg",
    description:
      "α-檀香醇流淌出奶油般柔滑暖意，缠绕烟熏甜香如焚香余烬，奠定东方木质调的深邃基底。",
    intensity: 6,
    freshness: 3,
    sweetness: 5,
    bitterness: 4,
    dryness: 8,
  },
  {
    name: "白檀香",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 3001,
    pinyin: "baitanxiang",
    src: "https://malfoy-mist.top/notes/baitanxiang.jpg",
    description:
      "β-檀香醇劈开清冽木香，溅出乳脂凉感与日光炙烤的干燥，支撑洁净木质尾调。",
    intensity: 6,
    freshness: 4,
    sweetness: 4,
    bitterness: 4,
    dryness: 7,
  },
  {
    name: "柏木",
    category: ["middle"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3002,
    pinyin: "baimu",
    src: "https://malfoy-mist.top/notes/baimu_x.jpg",
    description:
      "柏木烯释放松针尖锐绿意，裹挟树脂冷杉的粘稠触感，构筑森林中调干燥骨架。",
    intensity: 5,
    freshness: 5,
    sweetness: 3,
    bitterness: 5,
    dryness: 7,
  },
  {
    name: "柏树",
    category: ["middle"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3003,
    pinyin: "baishu",
    src: "https://malfoy-mist.top/notes/baishu.jpg",
    description:
      "雪松醇渗出铅笔屑般颗粒木香，混合尘土腐土气息，强化木质中调粗粝结构。",
    intensity: 5,
    freshness: 4,
    sweetness: 3,
    bitterness: 5,
    dryness: 7,
  },
  {
    name: "乌木",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 3004,
    pinyin: "wumu",
    src: "https://malfoy-mist.top/notes/wumu.jpg",
    description:
      "沉香醇蒸腾霉变皮革苦涩，β-沉香烯融成蜂蜜甘醇暖流，奠定东方香调烟熏核心。",
    intensity: 6,
    freshness: 3,
    sweetness: 5,
    bitterness: 6,
    dryness: 8,
  },
  {
    name: "金丝楠木",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3005,
    pinyin: "jinsinanmu",
    src: "https://malfoy-mist.top/notes/jinsinanmu.jpg",
    description:
      "楠木烯散发金丝光泽甜润，交织琥珀流淌的暖意，构成稀有木质基底奢华感。",
    intensity: 6,
    freshness: 4,
    sweetness: 6,
    bitterness: 3,
    dryness: 7,
  },
  {
    name: "沉香",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 3006,
    pinyin: "chenxiang",
    src: "https://malfoy-mist.top/notes/chenxiang_x.jpg",
    description:
      "沉香烯撬出潮湿腐土壤香，α-没药醇溅出焦糖烟熏甘苦，支撑东方木质调深邃底蕴。",
    intensity: 6,
    freshness: 3,
    sweetness: 5,
    bitterness: 5,
    dryness: 8,
  },
  {
    name: "超级雪松",
    category: ["middle", "base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3007,
    pinyin: "chaojixuesong",
    src: "https://malfoy-mist.top/notes/chaojixuesong.jpg",
    description:
      "雪松醇爆发冰雪凛冽触感，裹挟松脂粘稠暖流，平衡中基调干燥强度。",
    intensity: 6,
    freshness: 5,
    sweetness: 4,
    bitterness: 4,
    dryness: 7,
  },
  {
    name: "雪松",
    category: ["middle", "base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3008,
    pinyin: "xuesong",
    src: "https://malfoy-mist.top/notes/xuesong_x.jpg",
    description:
      "雪松烯释放新鲜刨花干爽，渗入冷杉针叶绿汁酸意，构筑清新木质中调活力。",
    intensity: 5,
    freshness: 6,
    sweetness: 3,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "云衫",
    category: ["top", "middle"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3009,
    pinyin: "yunshan",
    src: "https://malfoy-mist.top/notes/yunshan.jpg",
    description:
      "松油醇溅出松脂粘稠绿意，混合冷空气冰晶感，点亮木质前调尖锐清新。",
    intensity: 5,
    freshness: 7,
    sweetness: 3,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "松木",
    category: ["top", "middle"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3010,
    pinyin: "songmu",
    src: "https://malfoy-mist.top/notes/songmu.jpg",
    description:
      "α-蒎烯劈开松针酸香锐利，β-蒎烯融成树脂甜暖流淌，交织森林中调活力脉络。",
    intensity: 5,
    freshness: 6,
    sweetness: 4,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "奇楠",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 3011,
    pinyin: "qinan",
    src: "https://malfoy-mist.top/notes/qinan.jpeg",
    description:
      "沉香螺醇蒸腾薄荷凉意，缠绕蜂蜜琥珀甘醇暖流，奠定顶级东方木质核心复杂度。",
    intensity: 6,
    freshness: 5,
    sweetness: 6,
    bitterness: 5,
    dryness: 8,
  },
  {
    name: "参香",
    category: ["middle"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3012,
    pinyin: "canxiang",
    src: "https://malfoy-mist.top/notes/canxiang.jpg",
    description:
      "人参烯释放泥土根茎苦涩，混合药草甘甜触感，构筑独特木质中调药感骨架。",
    intensity: 5,
    freshness: 4,
    sweetness: 5,
    bitterness: 6,
    dryness: 7,
  },
  {
    name: "森林",
    category: ["middle"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3013,
    pinyin: "senlin",
    src: "https://malfoy-mist.top/notes/senlin.jpg",
    description:
      "蒎烯与雪松醇缠绕，爆出潮湿苔藓腐土湿冷，松油醇添加针叶绿汁酸意，模拟森林中调生态层次。",
    intensity: 5,
    freshness: 5,
    sweetness: 3,
    bitterness: 5,
    dryness: 7,
  },
  {
    name: "沉香木",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 3014,
    pinyin: "chenxiangmu",
    src: "https://malfoy-mist.top/notes/chenxiangmu.jpg",
    description:
      "沉香呋喃释放烟熏树脂底蕴，微咸皮革质感交织，厚重木质基底支撑香气持久度与层次感",
    intensity: 6,
    freshness: 4,
    sweetness: 4,
    bitterness: 5,
    dryness: 8,
  },
];

const note_4 = [
  {
    name: "焚香",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 4000,
    pinyin: "fenxiang",
    src: "https://malfoy-mist.top/notes/fenxiang_x.jpg",
    description:
      "愈创木酚熏烤出焦黑炭纹，乙酸龙脑酯升腾乳白烟柱，木质东方调烟熏核心基底",
    intensity: 7,
    freshness: 3,
    sweetness: 3,
    bitterness: 5,
    dryness: 8,
  },
  {
    name: "安息香",
    category: ["base"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "琥珀香调",
    global_id: 4001,
    pinyin: "anxixiang",
    src: "https://malfoy-mist.top/notes/anxixiang_x.jpg",
    description:
      "苯甲酸苄酯流淌香草蜜脂，肉桂酸结晶焦糖琥珀，东方调甜树脂暖融基座",
    intensity: 6,
    freshness: 2,
    sweetness: 7,
    bitterness: 3,
    dryness: 6,
  },
  {
    name: "乳香",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 4002,
    pinyin: "ruxiang",
    src: "https://malfoy-mist.top/notes/ruxiang.jpg",
    description: "α-蒎烯劈开松脂清冽，乙酸辛酯溅出柑橘冰晶，木质烟熏调空灵支柱",
    intensity: 6,
    freshness: 4,
    sweetness: 4,
    bitterness: 4,
    dryness: 7,
  },
  {
    name: "吐鲁香脂",
    category: ["base"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "琥珀香调",
    global_id: 4003,
    pinyin: "tuluxiangzhi",
    src: "https://malfoy-mist.top/notes/tuluxiangzhi.jpg",
    description:
      "肉桂酸乙酯穿刺辛甜热浪，苯甲酸沉淀杏仁奶冻，东方琥珀调稠厚包覆层",
    intensity: 6,
    freshness: 3,
    sweetness: 6,
    bitterness: 3,
    dryness: 7,
  },
  {
    name: "劳丹脂",
    category: ["base"],
    olfactory_family: "琥珀香调",
    sub_olfactory_family: "东方香调",
    global_id: 4004,
    pinyin: "laodanzhi",
    src: "https://malfoy-mist.top/notes/laodanzhi.jpg",
    description: "劳丹醇炙烤焦糖皮革，香豆素铺展干草暖甜，琥珀调深邃树脂光晕",
    intensity: 6,
    freshness: 2,
    sweetness: 7,
    bitterness: 4,
    dryness: 8,
  },
  {
    name: "丁子",
    category: ["middle", "base"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "",
    global_id: 4005,
    pinyin: "dingzi",
    src: "https://malfoy-mist.top/notes/dingzi.jpg",
    description: "丁香酚爆裂辛热铁锈，石竹烯缠绕药感粉雾，东方调穿透性辛香锚点",
    intensity: 7,
    freshness: 4,
    sweetness: 3,
    bitterness: 5,
    dryness: 6,
  },
  {
    name: "肉桂",
    category: ["middle", "base"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "",
    global_id: 4006,
    pinyin: "rougui",
    src: "https://malfoy-mist.top/notes/rougui_x.jpg",
    description:
      "肉桂醛点燃热辣糖浆，乙酸肉桂酯融化蜡质触感，东方调炽烈辛香脊柱",
    intensity: 7,
    freshness: 3,
    sweetness: 5,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "肉豆蔻",
    category: ["middle"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "",
    global_id: 4007,
    pinyin: "roudoukou",
    src: "https://malfoy-mist.top/notes/roudoukou_x.jpg",
    description:
      "肉豆蔻醚蒸腾暖甜粉尘，蒎烯萦绕干燥木质肌理，东方调微辛暖意中层",
    intensity: 6,
    freshness: 4,
    sweetness: 5,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "香根草",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 4008,
    pinyin: "xianggencao",
    src: "https://malfoy-mist.top/notes/xianggencao.jpg",
    description: "香根酮煅烧干燥烟丝，香根醇撬出湿土根茎，木质调深沉壤香地基",
    intensity: 6,
    freshness: 3,
    sweetness: 3,
    bitterness: 5,
    dryness: 8,
  },
  {
    name: "甘松",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 4009,
    pinyin: "gansong",
    src: "https://malfoy-mist.top/notes/gansong_x.jpg",
    description:
      "甘松香酮（＜0.5%）逸散动物腥臊，缬草酮凝结药感木屑，东方调野性基底",
    intensity: 6,
    freshness: 3,
    sweetness: 3,
    bitterness: 5,
    dryness: 8,
  },
  {
    name: "愈创木",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 4010,
    pinyin: "yuchuangmu",
    src: "https://malfoy-mist.top/notes/yuchuangmu_x.jpg",
    description:
      "丁香油酚熏烤焦木炭纹，愈创木烯沉淀皮革咸涩，木质调烟熏核心骨架",
    intensity: 7,
    freshness: 3,
    sweetness: 2,
    bitterness: 5,
    dryness: 8,
  },
  {
    name: "零陵香豆",
    category: ["base"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "美食调",
    global_id: 4011,
    pinyin: "linglingxiangdou",
    src: "https://malfoy-mist.top/notes/linglingxiangdou.jpg",
    description:
      "香豆素研磨甜豆粉霜，肉桂酸内酯滴落杏仁奶冻，美食东方调甜美包覆层",
    intensity: 6,
    freshness: 3,
    sweetness: 8,
    bitterness: 3,
    dryness: 6,
  },
  {
    name: "香茅",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "",
    global_id: 4012,
    pinyin: "xiangmao",
    src: "https://malfoy-mist.top/notes/xiangmao.jpg",
    description: "香茅醛劈开柠檬草锐利，香茅醇柔化青草汁液，柑橘调清新上扬利刃",
    intensity: 6,
    freshness: 8,
    sweetness: 3,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "杜松子",
    category: ["top", "middle"],
    olfactory_family: "芳香调",
    sub_olfactory_family: "木质调",
    global_id: 4013,
    pinyin: "dusongzi",
    src: "https://malfoy-mist.top/notes/dusongzi.jpg",
    description: "α-蒎烯刺出松针冷冽，月桂烯滚动青椒辛绿，芳香木质调清凉前奏",
    intensity: 5,
    freshness: 7,
    sweetness: 3,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "广藿香",
    category: ["middle", "base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调",
    global_id: 4014,
    pinyin: "guanghuoxiang",
    src: "https://malfoy-mist.top/notes/guanghuoxiang_x.jpg",
    description:
      "广藿香醇沉淀湿腐泥土，广藿香烯透出薄荷凉意，木质调药感凉苦基岩",
    intensity: 6,
    freshness: 4,
    sweetness: 3,
    bitterness: 6,
    dryness: 7,
  },
  {
    name: "小豆蔻",
    category: ["middle"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "",
    global_id: 4015,
    pinyin: "xiaodoukou",
    src: "https://malfoy-mist.top/notes/xiaodoukou.jpeg",
    description: "桉叶素挥发樟脑清冽，松油醇烘焙辛香暖粉，东方调清新辛香接榫",
    intensity: 5,
    freshness: 5,
    sweetness: 3,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "甘草",
    category: ["base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 4016,
    pinyin: "gancao",
    src: "https://malfoy-mist.top/notes/gancao.jpg",
    description:
      "甘草甜素熬煮黑糖药汁，茴香脑折射八角辛甜，美食调甘醇基底黏合剂",
    intensity: 5,
    freshness: 3,
    sweetness: 7,
    bitterness: 3,
    dryness: 6,
  },
];

const note_5 = [
  {
    name: "罗勒",
    category: ["top", "middle"],
    olfactory_family: "芳香调",
    sub_olfactory_family: "",
    global_id: 5001,
    pinyin: "luole",
    src: "https://malfoy-mist.top/notes/luole.jpg",
    description:
      "甲基胡椒酚点燃的辛麻绿焰里，芳樟醇渗出柠檬糖清甜尾韵，新鲜罗勒叶在指尖揉碎溅出青汁暴雨",
    intensity: 6,
    freshness: 7,
    sweetness: 4,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "芫荽（香菜）",
    category: ["top"],
    olfactory_family: "芳香调",
    sub_olfactory_family: "",
    global_id: 5002,
    pinyin: "yuansui（xiangcai）",
    src: "https://malfoy-mist.top/notes/yuansui（xiangcai）.jpg",
    description:
      "癸醛刺破的苦橘皮油囊喷溅瞬间，芳樟醇凝结成雨后石板缝钻出的凉雾，锋利绿意掠过鼻尖",
    intensity: 5,
    freshness: 8,
    sweetness: 2,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "鼠尾草",
    category: ["middle"],
    olfactory_family: "芳香调",
    sub_olfactory_family: "",
    global_id: 5016,
    pinyin: "shuweicao",
    src: "https://malfoy-mist.top/notes/shuweicao.jpg",
    description:
      "桉叶油素冰针扎透晒焦的鼠尾草绒毛堆，樟脑冷风卷起灰绿色药粉在舌根盘旋",
    intensity: 6,
    freshness: 6,
    sweetness: 2,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "薄荷",
    category: ["top"],
    olfactory_family: "芳香调",
    sub_olfactory_family: "",
    global_id: 5018,
    pinyin: "baohe",
    src: "https://malfoy-mist.top/notes/baohe_x.jpg",
    description:
      "薄荷脑结晶在舌尖炸裂成冰河，薄荷酮翠绿汁液沿喉管滑落时带起刺骨寒风",
    intensity: 6,
    freshness: 9,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "青草",
    category: ["top", "middle"],
    olfactory_family: "绿叶调",
    sub_olfactory_family: "",
    global_id: 5006,
    pinyin: "qingcao",
    src: "https://malfoy-mist.top/notes/qingcao_x.jpg",
    description:
      "叶醇喷溅出割草机刀锋下的汁液暴雨，青草醛凝成草尖垂落的露珠沁入腕间",
    intensity: 5,
    freshness: 8,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "绿叶",
    category: ["middle"],
    olfactory_family: "绿叶调",
    sub_olfactory_family: "",
    global_id: 5010,
    pinyin: "lvye",
    src: "https://malfoy-mist.top/notes/lvye.jpg",
    description:
      "反式-2-己烯醛撕裂嫩叶生青筋膜时，β-紫罗兰酮在伤口晕开天鹅绒紫雾",
    intensity: 5,
    freshness: 7,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "茶树",
    category: ["middle"],
    olfactory_family: "绿叶调",
    sub_olfactory_family: "芳香调",
    global_id: 5009,
    pinyin: "chashu",
    src: "https://malfoy-mist.top/notes/chashu.jpg",
    description:
      "松油烯锐利药感刺穿晨雾，桉叶油素裹挟尤加利枯叶在鼻腔刮起洁净风暴",
    intensity: 6,
    freshness: 7,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "艾草",
    category: ["middle"],
    olfactory_family: "绿叶调",
    sub_olfactory_family: "",
    global_id: 5011,
    pinyin: "aicao",
    src: "https://malfoy-mist.top/notes/aicao_x.jpg",
    description:
      "侧柏酮（＜0.1%）点燃的苦艾酒幽蓝火焰里，樟脑霜雾覆盖艾绒干燥的灰烬触感",
    intensity: 5,
    freshness: 6,
    sweetness: 2,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "芦荟",
    category: ["top"],
    olfactory_family: "绿叶调",
    sub_olfactory_family: "",
    global_id: 5012,
    pinyin: "luhui",
    src: "https://malfoy-mist.top/notes/luhui_x.jpg",
    description:
      "芦荟大黄素凝胶包裹的凉滑切片上，苯甲醛杏仁苦味被叶醇汁液冲刷成透明绿意",
    intensity: 5,
    freshness: 8,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "粉红胡椒",
    category: ["top"],
    olfactory_family: "辛香调",
    sub_olfactory_family: "",
    global_id: 5000,
    pinyin: "fenhonghujiao",
    src: "https://malfoy-mist.top/notes/fenhonghujiao_x.jpg",
    description:
      "β-石竹烯花椒麻刺在舌尖跳舞，柠檬烯迸裂的柑橘火花点燃胡椒果壳霓虹",
    intensity: 7,
    freshness: 7,
    sweetness: 2,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "纸莎草",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 5007,
    pinyin: "zhisuocao",
    src: "https://malfoy-mist.top/notes/zhisuocao.jpg",
    description:
      "广藿香醇潮湿腐土中钻出烟熏根须，乙酸香根酯裹挟陈年宣纸的霉甜絮语",
    intensity: 6,
    freshness: 3,
    sweetness: 3,
    bitterness: 5,
    dryness: 7,
  },
  {
    name: "树苔",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 5014,
    pinyin: "shutai",
    src: "https://malfoy-mist.top/notes/shutai.jpg",
    description:
      "橡苔提取物（＜0.1%）渗出苔藓吸饱雨水的腐殖酸香，树苔酮摩挲着阴生绿意的天鹅绒襁褓",
    intensity: 6,
    freshness: 3,
    sweetness: 2,
    bitterness: 5,
    dryness: 7,
  },
  {
    name: "白苔",
    category: ["base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 5017,
    pinyin: "baitai",
    src: "https://malfoy-mist.top/notes/baitai.jpg",
    description:
      "白麝香蒸汽熨过亚麻布的洁净绒毛间，龙涎酮咸雾游移成肌肤温度的薄纱",
    intensity: 5,
    freshness: 4,
    sweetness: 2,
    bitterness: 3,
    dryness: 6,
  },
  {
    name: "橙叶",
    category: ["middle"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "",
    global_id: 5004,
    pinyin: "chengye",
    src: "https://malfoy-mist.top/notes/chengye.jpg",
    description:
      "乙酸橙花酯蜜渍花瓣沉入苦橙叶油墨，芳樟醇清光穿刺叶脉青绿经络时的震颤",
    intensity: 5,
    freshness: 7,
    sweetness: 3,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "马鞭草",
    category: ["top"],
    olfactory_family: "柑橘调",
    sub_olfactory_family: "",
    global_id: 5019,
    pinyin: "mabiancao",
    src: "https://malfoy-mist.top/notes/mabiancao_x.jpg",
    description:
      "柠檬醛酸刃削开柠檬皮油囊刹那，香茅醛青涩草汁沿刀锋滴落成绿色闪电",
    intensity: 6,
    freshness: 8,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "香草",
    category: ["base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 5003,
    pinyin: "xiangcao",
    src: "https://malfoy-mist.top/notes/xiangcao.jpg",
    description:
      "香兰素融化的奶油瀑布裹住焦糖脆壳，乙基香兰素烟甜炙烤着上颚味蕾",
    intensity: 5,
    freshness: 3,
    sweetness: 8,
    bitterness: 2,
    dryness: 6,
  },
  {
    name: "竹子",
    category: ["top", "middle"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "",
    global_id: 5021,
    pinyin: "zhuzi",
    src: "https://malfoy-mist.top/notes/zhuzi_x.jpg",
    description: "西瓜酮剖开竹节涌出带涩青汁，芳樟醇清风卷起水雾在林间铺开绿瀑",
    intensity: 5,
    freshness: 7,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
];

const note_6 = [
  {
    name: "蜜糖",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6000,
    pinyin: "mitang",
    src: "https://malfoy-mist.top/notes/mitang_x.jpg",
    description:
      "乙基麦芽酚融化的琥珀色糖浆拉出金丝，呋喃酮焦糖脆壳在舌尖碎裂时爆出太妃糖暖流",
    intensity: 6,
    freshness: 3,
    sweetness: 8,
    bitterness: 2,
    dryness: 4,
  },
  {
    name: "蜂蜜",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6001,
    pinyin: "fengmi",
    src: "https://malfoy-mist.top/notes/fengmi_x.jpg",
    description:
      "苯乙酸蒸腾的蜂巢蜡质暖雾里，甲基苯乙醛携带野花蜜的酵酸尾韵渗入喉头黏稠回甘",
    intensity: 6,
    freshness: 3,
    sweetness: 7,
    bitterness: 2,
    dryness: 4,
  },
  {
    name: "苦咖啡",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "特殊香调",
    global_id: 6002,
    pinyin: "kukafei",
    src: "https://malfoy-mist.top/notes/kukafei.jpg",
    description:
      "吡嗪撬开烘焙过度的咖啡豆焦苦内核，硫醇（＜0.02%）的橡胶灼烟缠绕深烘油脂厚重感",
    intensity: 7,
    freshness: 2,
    sweetness: 3,
    bitterness: 8,
    dryness: 6,
  },
  {
    name: "香咖啡",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "特殊香调",
    global_id: 6003,
    pinyin: "xiangkafei",
    src: "https://malfoy-mist.top/notes/xiangkafei.jpg",
    description:
      "糠硫醇焦糖拿铁般丝滑奶泡下，咖啡呋喃酮渗出烤榛果的暖甜油脂包裹舌苔",
    intensity: 6,
    freshness: 3,
    sweetness: 6,
    bitterness: 5,
    dryness: 5,
  },
  {
    name: "巧克力",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6004,
    pinyin: "qiaokeli",
    src: "https://malfoy-mist.top/notes/qiaokeli.jpg",
    description:
      "可可碱苦粉簌簌落进香兰素熔岩，苯乙醛模拟可可脂在体温融化的丝绒触感",
    intensity: 6,
    freshness: 2,
    sweetness: 7,
    bitterness: 6,
    dryness: 5,
  },
  {
    name: "烈酒",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6005,
    pinyin: "liejiu",
    src: "https://malfoy-mist.top/notes/liejiu.jpg",
    description:
      "乙酸乙酯点燃的酒精蓝焰中，丁酸乙酯裹挟烂水果发酵酸气灼烧鼻腔黏膜",
    intensity: 8,
    freshness: 4,
    sweetness: 3,
    bitterness: 6,
    dryness: 5,
  },
  {
    name: "威士忌",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6006,
    pinyin: "weishiji",
    src: "https://malfoy-mist.top/notes/weishiji.jpg",
    description:
      "橡木内酯渗出的烟熏木桶水汽里，愈创木酚（＜0.001%）的消毒水锋芒刺穿蜂蜜甜幕",
    intensity: 7,
    freshness: 3,
    sweetness: 4,
    bitterness: 5,
    dryness: 6,
  },
  {
    name: "白兰地",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6007,
    pinyin: "bailandi",
    src: "https://malfoy-mist.top/notes/bailandi_x.jpg",
    description:
      "乙酸异戊酯蒸腾的葡萄腐烂甜香中，丁香酚辛辣暖流裹着橡木单宁涩感滑入食道",
    intensity: 7,
    freshness: 3,
    sweetness: 5,
    bitterness: 5,
    dryness: 5,
  },
  {
    name: "陈皮",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "柑橘调",
    global_id: 6008,
    pinyin: "chenpi",
    src: "https://malfoy-mist.top/notes/chenpi.jpg",
    description:
      "柠檬烯挥发油刺破陈皮霉衣瞬间，紫苏醛的草药苦韵混着晒干橘络粉尘扬起",
    intensity: 6,
    freshness: 7,
    sweetness: 4,
    bitterness: 5,
    dryness: 5,
  },
  {
    name: "杏仁",
    category: ["middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "东方香调",
    global_id: 6009,
    pinyin: "xingren",
    src: "https://malfoy-mist.top/notes/xingren.jpg",
    description:
      "苯甲醛苦味核仁被氢氰酸（＜0.01%）金属锋芒刺穿，香兰素糖霜在裂缝渗出奶甜",
    intensity: 6,
    freshness: 3,
    sweetness: 6,
    bitterness: 5,
    dryness: 5,
  },
  {
    name: "大白兔",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6010,
    pinyin: "dabaitu",
    src: "https://malfoy-mist.top/notes/dabaitu.jpeg",
    description:
      "炼乳香基裹着乙基香兰素奶糖外衣，麦芽酚焦香在唾液融化时拉出甜丝",
    intensity: 6,
    freshness: 3,
    sweetness: 8,
    bitterness: 2,
    dryness: 4,
  },
  {
    name: "纯牛奶",
    category: ["middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6011,
    pinyin: "chunniunai",
    src: "https://malfoy-mist.top/notes/chunniunai.jpg",
    description:
      "丁二酮黄油暖雾漫过δ-癸内酯的奶腥湿巾，乳脂肪球在舌面铺开天鹅绒膜",
    intensity: 5,
    freshness: 3,
    sweetness: 6,
    bitterness: 2,
    dryness: 3,
  },
  {
    name: "酸牛奶",
    category: ["middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6012,
    pinyin: "suanniunai",
    src: "https://malfoy-mist.top/notes/suanniunai.jpg",
    description:
      "乙酸撕开凝结乳清的酸腐裂口，双乙酰黄油腐臭被乳酸菌活体颤动平衡",
    intensity: 5,
    freshness: 4,
    sweetness: 4,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "大米",
    category: ["middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6013,
    pinyin: "dami",
    src: "https://malfoy-mist.top/notes/dami_x.jpg",
    description:
      "乙酰吡嗪爆米花焦香里钻出γ-壬内酯的椰奶甜雾，蒸锅水汽濡湿糙米表层糠粉",
    intensity: 5,
    freshness: 3,
    sweetness: 6,
    bitterness: 2,
    dryness: 4,
  },
  {
    name: "绿豆",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6014,
    pinyin: "lvdou",
    src: "https://malfoy-mist.top/notes/lvdou.jpg",
    description: "己醛劈开豆荚的青腥汁液，苯甲醛苦杏仁核在绿豆沙绵密粉感中隐现",
    intensity: 6,
    freshness: 5,
    sweetness: 4,
    bitterness: 6,
    dryness: 5,
  },
  {
    name: "黑醋栗",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6015,
    pinyin: "heiculi",
    src: "https://malfoy-mist.top/notes/heiculi_x.jpg",
    description:
      "对甲氧基苯丙酮的猫尿骚动被β-紫罗兰酮花瓣镇压，酒石酸刺破黑加仑膏的浓甜",
    intensity: 6,
    freshness: 6,
    sweetness: 6,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "意大利红酒",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6016,
    pinyin: "yidalihongjiu",
    src: "https://malfoy-mist.top/notes/yidalihongjiu.jpg",
    description:
      "酒石酸结晶刺穿单宁棉絮网，橡木内酯烟熏裹挟乙酸乙酯的烂葡萄酵酸",
    intensity: 7,
    freshness: 4,
    sweetness: 5,
    bitterness: 5,
    dryness: 5,
  },
  {
    name: "生姜",
    category: ["top", "middle"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 6018,
    pinyin: "shengjiang",
    src: "https://malfoy-mist.top/notes/shengjiang_x.jpg",
    description: "姜烯点燃的辛辣碳棒捅破柠檬醛酸膜，姜酚裹着纤维丝刮擦喉头灼痕",
    intensity: 8,
    freshness: 6,
    sweetness: 2,
    bitterness: 5,
    dryness: 5,
  },
];

const note_7 = [
  {
    name: "海盐",
    category: ["top"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "",
    global_id: 7000,
    pinyin: "haiyan",
    src: "https://malfoy-mist.top/notes/haiyan.png",
    description:
      "海盐醛迸发的咸晶粒劈开舌尖冷麻，浪花飞溅触感湿滑，铺陈海洋调清澈基底",
    intensity: 6,
    freshness: 8,
    sweetness: 2,
    bitterness: 3,
    dryness: 3,
  },
  {
    name: "海洋",
    category: ["top", "middle"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "",
    global_id: 7001,
    pinyin: "haiyang",
    src: "https://malfoy-mist.top/notes/haiyang.jpg",
    description:
      "Calone勾勒的水域辽阔感，西瓜酮清甜融化咸雾涩口，潮汐包裹四肢的凉意支撑水生韵律",
    intensity: 6,
    freshness: 8,
    sweetness: 4,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "海橡苔",
    category: ["base"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "木质调",
    global_id: 7002,
    pinyin: "haixiangtai",
    src: "https://malfoy-mist.top/notes/haixiangtai.jpg",
    description:
      "橡苔醛撬出的湿木腥咸，腐殖土绵密吸附如苔毯，交织海洋与木质尾调沉淀",
    intensity: 5,
    freshness: 4,
    sweetness: 2,
    bitterness: 4,
    dryness: 7,
  },
  {
    name: "海藻",
    category: ["middle", "base"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "",
    global_id: 7003,
    pinyin: "haizao",
    src: "https://malfoy-mist.top/notes/haizao_x.jpg",
    description:
      "溴代苏合香烯蒸腾的藻类滑腻，触手缠绕深水幽暗，咸鲜汁液渗出海洋调中后段",
    intensity: 5,
    freshness: 6,
    sweetness: 2,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "大海",
    category: ["top", "middle"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "",
    global_id: 7004,
    pinyin: "dahai",
    src: "https://malfoy-mist.top/notes/dahai.jpg",
    description:
      "二氢月桂烯醇席卷的咸风浩荡，烈日炙烤浪沫干涩刺喉，构筑广袤海域通透骨架",
    intensity: 7,
    freshness: 7,
    sweetness: 3,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "冷杉",
    category: ["middle", "base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "",
    global_id: 7005,
    pinyin: "lengshan",
    src: "https://malfoy-mist.top/notes/lengshan.jpg",
    description:
      "乙酸冰片酯劈开的松针凛冽，树脂流淌温润琥珀触感，木质调脊柱般坚实承托",
    intensity: 6,
    freshness: 5,
    sweetness: 2,
    bitterness: 3,
    dryness: 7,
  },
];

const note_8 = [
  {
    name: "玉龙茶",
    category: ["top", "middle"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8000,
    pinyin: "yulongcha",
    src: "https://malfoy-mist.top/notes/yulongcha.jpg",
    description:
      "芳樟醇冷雾裹挟雪峰凛冽，茶螺烷干草微涩刮过喉腔，茶调骨骼般嶙峋竖立",
    intensity: 6,
    freshness: 7,
    sweetness: 3,
    bitterness: 4,
    dryness: 5,
  },
  {
    name: "乌龙茶",
    category: ["middle"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8001,
    pinyin: "wulongcha",
    src: "https://malfoy-mist.top/notes/wulongcha.jpg",
    description:
      "β-紫罗兰果甜沉入焦木烟熏，吲哚（＜0.1%）青气如焙火撕裂，茶汤褐稠漫溢喉底",
    intensity: 6,
    freshness: 5,
    sweetness: 4,
    bitterness: 5,
    dryness: 6,
  },
  {
    name: "铁观音",
    category: ["middle"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8002,
    pinyin: "tieguanyin",
    src: "https://malfoy-mist.top/notes/tieguanyin.jpg",
    description:
      "茉莉酮酸甲酯兰韵透石，吲哚（＜0.1%）青气撬开矿石叮舌，岩骨硌出矿物咸鲜",
    intensity: 6,
    freshness: 5,
    sweetness: 3,
    bitterness: 5,
    dryness: 6,
  },
  {
    name: "红茶",
    category: ["middle"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8003,
    pinyin: "hongcha",
    src: "https://malfoy-mist.top/notes/hongcha.jpg",
    description:
      "乙基麦芽酚焦糖稠厚挂壁，茶黄素单宁褶皱摩擦上颚，发酵暖意裹住舌根微涩",
    intensity: 6,
    freshness: 5,
    sweetness: 5,
    bitterness: 5,
    dryness: 5,
  },
  {
    name: "白茶",
    category: ["top", "middle"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8004,
    pinyin: "baicha",
    src: "https://malfoy-mist.top/notes/baicha_x.jpg",
    description:
      "茴香醛的干草脆响簌簌剥落，白毫银针蒸腾水雾沁额，薄纱覆舌透出日光晒青",
    intensity: 5,
    freshness: 7,
    sweetness: 3,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "绿茶",
    category: ["top"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8005,
    pinyin: "lvcha",
    src: "https://malfoy-mist.top/notes/lvcha.jpg",
    description:
      "叶醇切割的草汁喷溅酸鲜，蒸青涩麻刺醒舌尖，杀青高温炙出嫩芽蜷曲",
    intensity: 5,
    freshness: 8,
    sweetness: 2,
    bitterness: 3,
    dryness: 4,
  },
  {
    name: "龙井茶",
    category: ["top", "middle"],
    olfactory_family: "茶香调",
    sub_olfactory_family: "",
    global_id: 8006,
    pinyin: "longjingcha",
    src: "https://malfoy-mist.top/notes/longjingcha.jpg",
    description:
      "栗酮烘炒暖意渗入芽芯，芳樟醇青气劈开晨露，嫩芽竖立如剑穿透水汽",
    intensity: 6,
    freshness: 7,
    sweetness: 3,
    bitterness: 4,
    dryness: 4,
  },
];

const note_9 = [
  {
    name: "琥珀",
    category: ["base"],
    olfactory_family: "琥珀香调",
    sub_olfactory_family: "",
    global_id: 9000,
    pinyin: "hupo",
    src: "https://malfoy-mist.top/notes/hupo.jpeg",
    description:
      "香兰素融成蜜丝拉黏齿龈，劳丹脂焦油滴落滚烫触感，日光稠厚裹住树脂垂坠",
    intensity: 7,
    freshness: 2,
    sweetness: 6,
    bitterness: 3,
    dryness: 6,
  },
];

const note_10 = [
  {
    name: "粉麝香",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9100,
    pinyin: "fenshexiang",
    src: "https://malfoy-mist.top/notes/fenshexiang_x.jpg",
    description:
      "环十五内酯粉雾蓬松吸附绒布触感，麝香酮体温暖意如旧棉絮包裹，动物调柔化基底棱角",
    intensity: 5,
    freshness: 2,
    sweetness: 2,
    bitterness: 2,
    dryness: 5,
  },
  {
    name: "麝香",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9101,
    pinyin: "shexiang",
    src: "https://malfoy-mist.top/notes/shexiang.jpg",
    description:
      "麝香酮蒸腾的体热氤氲，皮毛摩擦耳后微痒，原始欲念暗涌动物调核心",
    intensity: 7,
    freshness: 1,
    sweetness: 1,
    bitterness: 2,
    dryness: 6,
  },
  {
    name: "白麝香",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9102,
    pinyin: "baishexiang",
    src: "https://malfoy-mist.top/notes/baishexiang_x.jpg",
    description:
      "白麝香酮皂泡破裂溅出凉水触感，棉麻纤维洗净晒脆，洁净基底透亮无浊",
    intensity: 5,
    freshness: 5,
    sweetness: 1,
    bitterness: 1,
    dryness: 4,
  },
  {
    name: "龙涎香",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9103,
    pinyin: "longxianxiang",
    src: "https://malfoy-mist.top/notes/longxianxiang.png",
    description:
      "龙涎酮咸腥裹挟浪沫干涩刮喉，鲸脂融化日光黏腻垂坠，海洋动物调深邃沉淀",
    intensity: 8,
    freshness: 2,
    sweetness: 1,
    bitterness: 3,
    dryness: 7,
  },
  {
    name: "龙涎酮",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9104,
    pinyin: "longxiantong",
    src: "https://malfoy-mist.top/notes/longxiantong.jpg",
    description:
      "龙涎酮结晶析出盐粒硌舌，潮汐退去礁石矿冷触感，琥珀调骨架般硬朗承托",
    intensity: 7,
    freshness: 2,
    sweetness: 1,
    bitterness: 3,
    dryness: 6,
  },
  {
    name: "海狸",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9105,
    pinyin: "haili",
    src: "https://malfoy-mist.top/notes/haili.jpg",
    description:
      "对甲酚（＜0.3%）兽穴湿毛闷热，麝香掩映下腹暖腥淤积，动物调原始躁动",
    intensity: 7,
    freshness: 1,
    sweetness: 1,
    bitterness: 3,
    dryness: 7,
  },
];

const note_11 = [
  {
    name: "墨汁",
    category: ["base"],
    olfactory_family: "特殊香调",
    sub_olfactory_family: "",
    global_id: 9200,
    pinyin: "mozhi",
    src: "https://malfoy-mist.top/notes/mozhi_x.jpg",
    description:
      "苯酚墨汁泼溅金属涩口，宣纸吸湿晕染洇开，特殊调暗黑纹理如夜吞噬",
    intensity: 7,
    freshness: 1,
    sweetness: 1,
    bitterness: 5,
    dryness: 7,
  },
  {
    name: "烤面包",
    category: ["middle", "base"],
    olfactory_family: "美食调",
    sub_olfactory_family: "",
    global_id: 9201,
    pinyin: "kaomianbao",
    src: "https://malfoy-mist.top/notes/kaomianbao.jpg",
    description:
      "乙基麦芽酚焦糖脆皮崩裂热烫，面团发酵酸香扑鼻，美食调饱足感填满口腔",
    intensity: 6,
    freshness: 4,
    sweetness: 6,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "含羞草",
    category: ["middle"],
    olfactory_family: "花香调",
    sub_olfactory_family: "",
    global_id: 9202,
    pinyin: "hanxiucao",
    src: "https://malfoy-mist.top/notes/hanxiucao_x.jpg",
    description:
      "金合欢醇绒球轻颤粉痒触感，青草汁液渗出茎管微酸，花调羞怯闪烁晨光",
    intensity: 5,
    freshness: 6,
    sweetness: 5,
    bitterness: 2,
    dryness: 4,
  },
  {
    name: "乌木与佛手柑",
    category: ["middle", "base"],
    olfactory_family: "木质调",
    sub_olfactory_family: "东方香调/柑橘调",
    global_id: 9203,
    pinyin: "wumuyufoshougan",
    src: "https://malfoy-mist.top/notes/wumuyufoshougan.jpg",
    description:
      "沉香醇乌木烟熏缠绕佛手柑酸汁飞溅，柑橘木质碰撞火花噼啪，调性冲突中融合",
    intensity: 7,
    freshness: 5,
    sweetness: 3,
    bitterness: 4,
    dryness: 6,
  },
  {
    name: "贝香",
    category: ["middle"],
    olfactory_family: "海洋水生调",
    sub_olfactory_family: "",
    global_id: 9204,
    pinyin: "beixiang",
    src: "https://malfoy-mist.top/notes/beixiang_x.jpg",
    description:
      "溴代苏合香烯贝肉滑腻撬开，咸汁滴落沙滩钙粒粗粝，海洋调残壳吸附盐晶",
    intensity: 6,
    freshness: 6,
    sweetness: 2,
    bitterness: 3,
    dryness: 5,
  },
  {
    name: "皮革",
    category: ["base"],
    olfactory_family: "动物香调",
    sub_olfactory_family: "",
    global_id: 9205,
    pinyin: "pige",
    src: "https://malfoy-mist.top/notes/pige.jpg",
    description:
      "异丁基喹啉鞣制皮面油亮反光，马鞍汗渍渗透闷热，动物调粗粝摩擦肌肤",
    intensity: 7,
    freshness: 1,
    sweetness: 2,
    bitterness: 3,
    dryness: 6,
  },
  {
    name: "烟草",
    category: ["base"],
    olfactory_family: "东方香调",
    sub_olfactory_family: "",
    global_id: 9206,
    pinyin: "yancao",
    src: "https://malfoy-mist.top/notes/yancao_x.jpg",
    description:
      "烟碱焦油涂抹喉腔干灼刺痛，烟叶揉碎褐粉飞扬呛鼻，东方调辛辣余烬闷燃",
    intensity: 7,
    freshness: 2,
    sweetness: 2,
    bitterness: 4,
    dryness: 6,
  },
];

// 合并所有数组
const allNotes = [
  ...note_1,
  ...note_2,
  ...note_3,
  ...note_4,
  ...note_5,
  ...note_6,
  ...note_7,
  ...note_8,
  ...note_9,
  ...note_10,
  ...note_11,
];

export default allNotes;
