/**
 * 
 * 完全可以。我们可以做一个完整的香材数据库 Excel，每个香材包含你需要的五个字段：

volatility（high/medium/low）

impact_level（high/medium/low）

buffer_required（boolean）

solo_max_ratio（相对于香精总量 % 上限，可调）

structural_power（0–1，承重能力）

原则如下，我会严格按照香材特性生成：

香材类别	            volatility	impact_level	buffer_required	 solo_max_ratio (%)	 structural_power
高爆发柑橘/青草/薄荷	  high	      high	        true	          1–4	                 0.2–0.3
中调水果/花香	         medium	     medium	       false	         3–8	                0.3–0.5
木质/麝香/香脂/基础香料	low	        low	          false	          10–30	                0.7–1
奶香/酒香/可食香材	    medium	    medium	     false	         5–10	                 0.4–0.6
*/

const perfumeMaterialsDatabase = [
  {
    global_id: 1001,
    name: "青柠",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.2,
  },
  {
    global_id: 1003,
    name: "柑橘",
    category: ["top"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 2,
    structural_power: 0.2,
  },
  {
    global_id: 1004,
    name: "青柚",
    category: ["top"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 2,
    structural_power: 0.2,
  },
  {
    global_id: 1005,
    name: "佛手柑",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 3.0,
    structural_power: 0.2,
  },
  {
    global_id: 1006,
    name: "香柠檬",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.2,
  },
  {
    global_id: 1007,
    name: "橘子",
    category: ["top"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 2,
    structural_power: 0.2,
  },
  {
    global_id: 1008,
    name: "莱姆",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.2,
  },
  {
    global_id: 1009,
    name: "酸橙",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.2,
  },
  {
    global_id: 1010,
    name: "血橙",
    category: ["top"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 2,
    structural_power: 0.2,
  },
  {
    global_id: 6007,
    name: "白兰地",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 6008,
    name: "陈皮",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 1011,
    name: "甜橙",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3,
    structural_power: 0.3,
  },
  {
    global_id: 1012,
    name: "葡萄柚",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3,
    structural_power: 0.3,
  },
  {
    global_id: 1013,
    name: "柚子-葡萄柚",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3.5,
    structural_power: 0.3,
  },
  {
    global_id: 1021,
    name: "西柚",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3,
    structural_power: 0.3,
  },
  {
    global_id: 1000,
    name: "橄榄",
    category: ["top"],
    volatility: "medium",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 3,
    structural_power: 0.5,
  },
  {
    global_id: 1002,
    name: "青苹果",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3,
    structural_power: 0.3,
  },
  {
    global_id: 1015,
    name: "黄瓜",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 3,
    structural_power: 0.4,
  },
  {
    global_id: 1018,
    name: "樱桃",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1023,
    name: "荔枝",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1024,
    name: "葡萄",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1025,
    name: "草莓",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1026,
    name: "蓝莓",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1027,
    name: "黑加侖子",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1033,
    name: "覆盆子",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1020,
    name: "水蜜桃",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1022,
    name: "李子",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1034,
    name: "洋梨",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1030,
    name: "苹果",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1014,
    name: "香蕉",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1016,
    name: "百香果",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2015,
    name: "忍冬花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2016,
    name: "丁香",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2017,
    name: "勿忘我",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2018,
    name: "睡莲",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2019,
    name: "薰衣草",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2020,
    name: "胡姬花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2021,
    name: "风信子",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2022,
    name: "郁金香",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2023,
    name: "姜花（蝴蝶花）",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2025,
    name: "山茶花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2026,
    name: "牡丹",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2027,
    name: "洛神花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2028,
    name: "罂粟花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2029,
    name: "依兰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2030,
    name: "橙花",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2031,
    name: "铃兰",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2032,
    name: "紫罗兰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2033,
    name: "金银花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2034,
    name: "兰花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2035,
    name: "桃花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2036,
    name: "桂花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2037,
    name: "黄葵",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2038,
    name: "栀子花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2039,
    name: "白玉兰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2040,
    name: "樱花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2041,
    name: "梅花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 3005,
    name: "金丝楠木",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 3006,
    name: "沉香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 3007,
    name: "超级雪松",
    category: ["middle", "base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 3008,
    name: "雪松",
    category: ["middle"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 3009,
    name: "云衫",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 3010,
    name: "松木",
    category: ["top", "middle"],
    volatility: "high",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 3.0,
    structural_power: 0.4,
  },
  {
    global_id: 3011,
    name: "奇楠",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.95,
  },
  {
    global_id: 3012,
    name: "参香",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 3013,
    name: "森林",
    category: ["middle"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 4000,
    name: "焚香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 4001,
    name: "安息香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 4002,
    name: "乳香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 4003,
    name: "吐鲁香脂",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 4004,
    name: "劳丹脂",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 4005,
    name: "丁子",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 4006,
    name: "肉桂",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 4007,
    name: "肉豆蔻",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 4008,
    name: "香根草",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 4009,
    name: "甘松",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 4010,
    name: "愈创木",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 4011,
    name: "零陵香豆",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 4012,
    name: "香茅",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 2,
    structural_power: 0.2,
  },
  {
    global_id: 4013,
    name: "杜松子",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 4014,
    name: "广霍香",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 4015,
    name: "小豆蔻",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 4016,
    name: "甘草",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 4018,
    name: "薄荷",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 3.0,
    structural_power: 0.2,
  },
  {
    global_id: 5000,
    name: "粉红胡椒",
    category: ["top"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.2,
  },
  {
    global_id: 5001,
    name: "罗勒",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 5002,
    name: "芫荽（香菜）",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.3,
  },
  {
    global_id: 5003,
    name: "香草",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 15,
    structural_power: 0.8,
  },
  {
    global_id: 5004,
    name: "橙叶",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 3,
    structural_power: 0.4,
  },
  {
    global_id: 5005,
    name: "风铃草",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 5006,
    name: "青草",
    category: ["top", "middle"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 3.0,
    structural_power: 0.2,
  },
  {
    global_id: 5007,
    name: "纸莎草",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 5009,
    name: "茶树",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 5010,
    name: "绿叶",
    category: ["middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 3,
    structural_power: 0.4,
  },
  {
    global_id: 5011,
    name: "艾草",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 5012,
    name: "芦荟",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 3,
    structural_power: 0.4,
  },
  {
    global_id: 5014,
    name: "树苔",
    category: ["base"],
    volatility: "low",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.8,
  },
  {
    global_id: 5017,
    name: "白苔",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 5018,
    name: "薄荷",
    category: ["top"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 3.0,
    structural_power: 0.2,
  },
  {
    global_id: 5019,
    name: "马鞭草",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 2,
    structural_power: 0.3,
  },
  {
    global_id: 5021,
    name: "竹子",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 6000,
    name: "蜜糖",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 6001,
    name: "蜂蜜",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 6002,
    name: "苦咖啡",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 6003,
    name: "香咖啡",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 6004,
    name: "巧克力",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 6005,
    name: "烈酒",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 6006,
    name: "威士忌",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 7000,
    name: "海盐",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.3,
  },
  {
    global_id: 7001,
    name: "海洋",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 7002,
    name: "海橡苔",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 7003,
    name: "海藻",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.5,
  },
  {
    global_id: 7004,
    name: "大海",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 7005,
    name: "冷杉",
    category: ["middle", "base"],
    volatility: "low",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.8,
  },
  {
    global_id: 8000,
    name: "玉龙茶",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 8001,
    name: "乌龙茶",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 8002,
    name: "铁观音",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 8003,
    name: "红茶",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 8004,
    name: "白茶",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 8005,
    name: "绿茶",
    category: ["top"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 3,
    structural_power: 0.4,
  },
  {
    global_id: 8006,
    name: "龙井茶",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 9000,
    name: "琥珀",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 9001,
    name: "安息香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.9,
  },
  {
    global_id: 9100,
    name: "粉麝香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 9101,
    name: "麝香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 9102,
    name: "白麝香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 9103,
    name: "龙涎香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 9104,
    name: "龙涎酮",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 9105,
    name: "海狸",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 9200,
    name: "墨汁",
    category: ["base"],
    volatility: "low",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.9,
  },
  {
    global_id: 9201,
    name: "烤面包",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 9202,
    name: "含羞草",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 9203,
    name: "乌木与佛手柑",
    category: ["middle", "base"],
    volatility: "low",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 9204,
    name: "贝香",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.5,
  },
  {
    global_id: 9205,
    name: "皮革",
    category: ["base"],
    volatility: "low",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.9,
  },
  {
    global_id: 9206,
    name: "烟草",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.9,
  },
  {
    global_id: 6009,
    name: "杏仁",
    category: ["middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 6010,
    name: "大白兔",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.5,
  },
  {
    global_id: 6011,
    name: "纯牛奶",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.5,
  },
  {
    global_id: 6012,
    name: "酸牛奶",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.5,
  },
  {
    global_id: 6013,
    name: "大米",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.4,
  },
  {
    global_id: 6014,
    name: "绿豆",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 6015,
    name: "黑醋栗",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 6016,
    name: "意大利红酒",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.5,
  },
  {
    global_id: 6018,
    name: "生姜",
    category: ["top", "middle"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 2.5,
    structural_power: 0.25,
  },
  {
    global_id: 2042,
    name: "水仙花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2043,
    name: "鸡蛋花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 2044,
    name: "海棠花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2045,
    name: "百合花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 2046,
    name: "鸢尾花",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.5,
  },
  {
    global_id: 2024,
    name: "甘菊",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2047,
    name: "洋甘菊",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2048,
    name: "百里香",
    category: ["top", "middle"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.25,
  },
  {
    global_id: 2049,
    name: "马郁兰",
    category: ["middle"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3,
    structural_power: 0.25,
  },
  {
    global_id: 2050,
    name: "迷迭香",
    category: ["top", "middle"],
    volatility: "high",
    impact_level: "high",
    buffer_required: true,
    solo_max_ratio: 4,
    structural_power: 0.25,
  },
  {
    global_id: 2051,
    name: "月桂",
    category: ["middle"],
    volatility: "high",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 3,
    structural_power: 0.25,
  },
  {
    global_id: 2054,
    name: "藏红花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: true,
    solo_max_ratio: 20,
    structural_power: 0.3,
  },
  {
    global_id: 2052,
    name: "小苍兰",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2053,
    name: "田野花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2055,
    name: "菊花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2056,
    name: "太阳花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2057,
    name: "蓝风铃",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2058,
    name: "天竺葵",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 3000,
    name: "檀香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.85,
  },
  {
    global_id: 3001,
    name: "白檀香",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 20,
    structural_power: 0.8,
  },
  {
    global_id: 3002,
    name: "柏木",
    category: ["middle"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 18,
    structural_power: 0.8,
  },
  {
    global_id: 3003,
    name: "柏树",
    category: ["middle"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 18,
    structural_power: 0.8,
  },
  {
    global_id: 3004,
    name: "乌木",
    category: ["base"],
    volatility: "low",
    impact_level: "low",
    buffer_required: false,
    solo_max_ratio: 25,
    structural_power: 0.95,
  },
  {
    global_id: 1017,
    name: "西瓜",
    category: ["top", "middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.35,
  },
  {
    global_id: 1028,
    name: "哈密瓜",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 1029,
    name: "菠萝",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 1019,
    name: "无花果",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.4,
  },
  {
    global_id: 1031,
    name: "椰子",
    category: ["middle", "base"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.5,
  },
  {
    global_id: 1032,
    name: "杏仁",
    category: ["base"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.6,
  },
  {
    global_id: 2000,
    name: "红玫瑰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.45,
  },
  {
    global_id: 2001,
    name: "白玫瑰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 2002,
    name: "保加利亚玫瑰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 7,
    structural_power: 0.5,
  },
  {
    global_id: 2003,
    name: "五月玫瑰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.45,
  },
  {
    global_id: 2004,
    name: "粉玫瑰",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 2005,
    name: "蔷薇",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 2006,
    name: "晚香玉",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.45,
  },
  {
    global_id: 2007,
    name: "白兰花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 5,
    structural_power: 0.4,
  },
  {
    global_id: 2008,
    name: "茉莉",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.45,
  },
  {
    global_id: 2009,
    name: "阿拉伯茉莉",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 6,
    structural_power: 0.45,
  },
  {
    global_id: 2010,
    name: "荷花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "high",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
  {
    global_id: 2011,
    name: "木棉花",
    category: ["middle"],
    volatility: "medium",
    impact_level: "medium",
    buffer_required: false,
    solo_max_ratio: 4,
    structural_power: 0.4,
  },
];

export default perfumeMaterialsDatabase;
